[{"content": {"molecule": [],
              "reagent": [{"concentration": "225.315E-6:%",
                           "id": 1,
                           "name": "e1 (Glycerol)"},
                          {"concentration": "1.7744E-12:g/L",
                           "id": 395,
                           "name": "e395 (Chloramphenicol)"},
                          {"concentration": "1.8E0:g/L",
                           "id": 394,
                           "name": "e394 (Kanamycin Sulfate)"},
                          {"concentration": "199.996E-3:%",
                           "id": 403,
                           "name": "e403 (D-(+)-Glucose (Dextrose))"},
                          {"concentration": "900.0E-3:X",
                           "id": 20,
                           "name": "e20 (Dulbeccos Phosphate Buffered Saline (DPBS Modified))"},
                          {"concentration": "9.799779E0:%",
                           "id": 678,
                           "name": "e678 (Supplemented M9 medium, no carbon source)"}],
              "strain": [{"id": 194570, "name": "t194570"}]},
  "measurements": {"7192": {"assay_type": "FACS",
                          "dataset_files": {"raw": [["attachments/sraw/e7192/8311615.sraw"],
                                                    ["attachments/fcs/e7192/8311615.fcs"]]},
                          "instrument": null,
                          "instrument_type": ["InstrumentType",
                                              20,
                                              "SA3800-Analyzer",
                                              null],
                          "measurement_name": "E. coli NAND gate characterization"}},
  "properties": {"SD2_incubation_temperature": "37:centigrade",
                 "SD2_replicate": 0,
                 "SD2_timepoint": "5:hours"},
  "sample_id": 8311615}]