[{"content": {"molecule": [],
              "reagent": [{"concentration": "225.315E-6:%",
                           "id": 1,
                           "name": "e1 (Glycerol)"},
                          {"concentration": "1.7744E-12:g/L",
                           "id": 395,
                           "name": "e395 (Chloramphenicol)"},
                          {"concentration": "1.8E0:g/L",
                           "id": 394,
                           "name": "e394 (Kanamycin Sulfate)"},
                          {"concentration": "199.996E-3:%",
                           "id": 403,
                           "name": "e403 (D-(+)-Glucose (Dextrose))"},
                          {"concentration": "900.0E-3:X",
                           "id": 20,
                           "name": "e20 (Dulbeccos Phosphate Buffered Saline (DPBS Modified))"},
                          {"concentration": "9.799779E0:%",
                           "id": 678,
                           "name": "e678 (Supplemented M9 medium, no carbon source)"}],
              "strain": [{"id": 194570, "name": "t194570"}]},
  "measurements": {"6980": {"assay_type": "Plate Reader Assay",
                          "dataset_files": {"processed": [["attachments/biotek_multi_csv/e6980/c151390.txt"]],
                                            "raw": [["attachments/biotek_multi_csv/e6980/c151390.txt"]]},
                          "instrument": ["Instrument",
                                         33,
                                         "Biotek Synergy H1m - Reader 5 | ayeaye-pc | Aye Aye in 25E",
                                         null],
                          "instrument_type": null,
                          "measurement_name": "NC NAND Platereader"},
                   "6995": {"assay_type": "Plate Reader Assay",
                          "dataset_files": {"processed": [["attachments/biotek_multi_csv/e6995/c151390.txt"],
                                                          ["attachments/biotek_multi_csv/e6995/c151390_I8CbN6y.txt"]],
                                            "raw": [["attachments/biotek_multi_csv/e6995/c151390.txt"],
                                                    ["attachments/biotek_multi_csv/e6995/c151390_I8CbN6y.txt"]]},
                          "instrument": ["Instrument",
                                         33,
                                         "Biotek Synergy H1m - Reader 5 | ayeaye-pc | Aye Aye in 25E",
                                         null],
                          "instrument_type": null,
                          "measurement_name": "NC NAND Platereader re-upload"}},
  "properties": {"SD2_incubation_temperature": "37:centigrade",
                 "SD2_replicate": 0,
                 "SD2_timepoint": "5:hours"},
  "sample_id": 8310784}]