[{"content": {"molecule": [],
              "reagent": [{"concentration": "99.795E-12:g/L",
                           "id": 394,
                           "name": "e394 (Kanamycin Sulfate)"},
                          {"concentration": "3.992E-3:%",
                           "id": 403,
                           "name": "e403 (D-(+)-Glucose (Dextrose))"},
                          {"id": 2420,
                           "name": "e2420 (7M Urea & 2M Thiourea Proteomics Lysis Buffer)"},
                          {"concentration": "195.604E-3:%",
                           "id": 678,
                           "name": "e678 (Supplemented M9 medium, no carbon source)"},
                          {"concentration": "4.497E-6:%",
                           "id": 1,
                           "name": "e1 (Glycerol)"},
                          {"concentration": "35.417E-15:g/L",
                           "id": 395,
                           "name": "e395 (Chloramphenicol)"}],
              "strain": [{"id": 194570, "name": "t194570"}]},
  "measurements": {"7316": {"TMT_channel": "TMT10-128C",
                          "assay_type": "Global Proteomics",
                          "dataset_files": {"processed": [[]], "raw": [[]]},
                          "instrument": null,
                          "instrument_type": ["InstrumentType",
                                              3,
                                              "LCMS Quad-Orbitrap Q-Exactive Plus",
                                              null],
                          "measurement_name": "s27 Global Proteomics with Relative Quantification for w14096 (QE+)"},
                   "7317": {"TMT_channel": "TMT10-128C",
                          "assay_type": "Global Proteomics",
                          "dataset_files": {"processed": [["/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.130.1397.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935-peptides.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.127.1235.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.128.1268.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.128.1331.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.129.1301.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.127.1298.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935-proteins.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.126.1264.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.131.1367.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.130.1335.peaks.csv",
                                                           "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML.sic.129.1364.peaks.csv"]],
                                            "raw": [["/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.mzML",
                                                     "/ginkgo/bitome/data/foundry/test/proteomics/exp7317/exp7317-34-ds6096935.msf"]]},
                          "instrument": null,
                          "instrument_type": ["InstrumentType",
                                              3,
                                              "LCMS Quad-Orbitrap Q-Exactive Plus",
                                              null],
                          "measurement_name": "s27 Global Proteomics with Relative Quantification for w14096 (QE HF-X)"}},
  "properties": {"SD2_incubation_temperature": "37:centigrade",
                 "SD2_replicate": 0,
                 "SD2_timepoint": "5:hours"},
  "sample_id": 8309785}]